Updated intro.md with cleaner intro message
cat-dev-group/catcord pull request #100
Opened 2021-07-23 21:58 UTC by AbooMinister25

Added a cleaner intro message for intro.md.

2021-07-28 16:05 UTC, dawnofmidnight requested changes

2021-07-28 16:05 UTC, dawnofmidnight commented on docs/docs/see-also/contributing.md
> +## Testing
This section is a bit unclear with the wording, so maybe something like this would be better

<hr>

Catcord uses [Docker](https://docker.com) for deployment, so it would be best that you test with Docker before opening a PR. You can start the containers in their respective directories with these commands.

Frontend:
```
docker build . -t frontend
docker run -p 3000:3000 frontend
```

Backend:
```
docker build . -t backend
docker run -p 8000:8000 backend
```

You can also start all of the containers with [Docker Compose](https://docs.docker.com/compose/) with this command in the root directory:
```
docker-compose up --build
```

2021-07-28 16:05 UTC, dawnofmidnight commented on docs/docs/see-also/contributing.md
> +## Linting
Again, I think this section could go on the respective frontend and backend pages.

2021-07-29 22:02 UTC, dawnofmidnight commented
I'll add a way to make the API reference soon so that the backend team can update that at their leisure.

2021-07-29 22:49 UTC, dawnofmidnight commented
An API reference section has now been added, and the backend team can populate that as they work.

2021-07-29 23:00 UTC, doublevcodes approved these changes

2021-07-29 23:29 UTC, merged