Revamp Backend Draft.
cat-dev-group/catcord pull request #103
Opened 2021-07-25 18:28 UTC by AbooMinister25

This is the draft for revamping the backend to follow our spec.

2021-07-28 18:08 UTC, Kronifer commented
I'm going to be working on IP stuff from this branch, if that's ok

2021-07-28 21:39 UTC, Kronifer submitted a review, later dismissed
Looks Great!!!

2021-07-28 21:45 UTC, doublevcodes requested changes
Seems like a great PR

2021-07-28 21:45 UTC, doublevcodes commented on backend/pyproject.toml
> +aerich = "^0.5.5"
Is this required?

2021-07-28 21:45 UTC, doublevcodes commented on backend/src/core/utils.py
> +    return hash
`hash` is a built-in, could we perhaps think of a different name for this? `hashed`?

2021-07-28 21:45 UTC, doublevcodes commented on backend/src/database/crud/users.py
> +        return False
It is possible to condense this into one conditional using the walrus operator.

2021-07-28 21:45 UTC, doublevcodes commented on backend/src/database/crud/users.py
> +        return None
Can be condensed using walrus operator

2021-07-28 21:45 UTC, doublevcodes commented on backend/src/database/crud/users.py
> +        return True
Can be condensed using walrus operator.

2021-07-28 21:45 UTC, doublevcodes commented on backend/src/database/crud/users.py
> +        return False
I think you get the idea

2021-07-28 21:45 UTC, doublevcodes commented on backend/src/database/models.py
> +        return self.name
Since you repeat this, maybe you could make it a separate ABC or something, something that makes it automatically use the name attribute

2021-07-28 21:45 UTC, doublevcodes commented on backend/src/endpoints/messages.py
> +    logger.info(f"GET request to endpoint /users from client {request.client.host}")
The logging doesn't match here.

2021-07-28 21:45 UTC, doublevcodes commented on backend/src/endpoints/users.py
> +        return HTTPException(status_code=403, detail="UID does not exist")
Condensable :^

2021-07-28 21:45 UTC, doublevcodes commented on backend/src/main.py
> +        return HTTPException(status_code=403, detail="Invalid Credentials")
:walrus:

2021-07-28 21:47 UTC, Evorage0 requested changes
I dont know how to show points in the file like rick did but:

In our token endpoint, we are authenticating the user and then updating the token however in the update token function we are **again** authenticating the user pointlessly
Suggested Edit: Remove the authentication in the update token function

In the `authorize_user` function in `database/crud/users.py` we perform two database calls when we only need to do it once
Suggested Edit: Remove `exists = await Users.filter(user_id=uid).exists()` and simply get the user, we know if it exists by checking if the result isnt `None`, then we dont have to query the db again for the actual user info

2021-07-28 22:04 UTC, Kronifer requested changes
I see one small problem not covered by the other reviews, otherwise it's looking good!

2021-07-28 22:04 UTC, Kronifer commented on backend/src/database/crud/users.py
> +    )
I see an indentation problem here, and these two statements are styled differently, can we please come up with consistency here please?

2021-07-28 22:06 UTC, Kronifer commented on backend/pyproject.toml
> +aerich = "^0.5.5"
From what I've seen throughout the PR, yes

2021-07-28 22:22 UTC, AbooMinister25 commented on backend/src/database/crud/users.py
> +    )
This is consistent, it's what black did.

2021-07-28 22:25 UTC, Kronifer commented on backend/src/database/crud/users.py
> +    )
Alright

2021-07-29 00:18 UTC, doublevcodes requested changes

2021-07-29 00:18 UTC, doublevcodes commented on backend/src/core/utils.py
>          token_count = 0
```suggestion
    token_count %= 256
```
I think this would work

2021-07-29 00:20 UTC, AbooMinister25 commented on backend/src/core/utils.py
>          token_count = 0
huh?

2021-07-29 00:20 UTC, AbooMinister25 commented on backend/src/core/utils.py
>          token_count = 0
Why would that work

2021-07-29 00:30 UTC, AbooMinister25 commented on backend/src/core/utils.py
>          token_count = 0
Ah I get it

2021-07-29 10:39 UTC, Evorage0 commented on backend/src/database/crud/users.py
> +    return user.username
Unnecessary query of the database twice, could improve like this
Also specifying that its **public** info since plans suggest we need another one for **private** info
```py
async def get_public_user_info(uid: str) -> Union[str, None]:
    logger.info(f"Attempting to get public user info for user with UID {uid}")

    user = await Users.filter(user_id=uid).first()
    if not user:
        logger.info(f"No user with UID {uid}")
        return False
    
    logger.success(f"Successfully retrived public user info for user with UID {uid}")
    return user.username
```

2021-07-29 10:39 UTC, Evorage0 commented on backend/src/database/crud/users.py
> +async def authorize_user(password: str, uid: str) -> bool:
The `authorize_user` should be renamed `auth_with_password` since its distinguishing from the function that auth's with token

2021-07-29 10:39 UTC, Evorage0 commented on backend/src/database/crud/users.py
> +async def auth_token(token: str, uid: int) -> bool:
small change to be more consistent, rename `auth_token` function to `auth_with_token` for readability and to fit the planned `auth_with_password` function

2021-07-29 10:39 UTC, Evorage0 commented on backend/src/endpoints/users.py
> +    username = await users.get_user_info(user_id)
Change (or add comment for future) that `username` is actually `user_info` since its planned that we are returning more then just the username. Not implemented yet tho so i guess it passes \:)

2021-07-29 10:39 UTC, Evorage0 commented on backend/src/endpoints/users.py
> +    await users.create_user(username, password_hash, email, uid, token)
Dont we need to hash the token?
add `token_hash = utils.generate_sha256(token)`

2021-07-29 14:40 UTC, AbooMinister25 commented on backend/src/endpoints/users.py
> +    await users.create_user(username, password_hash, email, uid, token)
Oh yeah, we do, I'll get on that

2021-07-29 14:40 UTC, AbooMinister25 commented on backend/src/database/crud/users.py
> +    return user.username
Got it

2021-07-29 14:41 UTC, AbooMinister25 commented on backend/src/database/crud/users.py
> +async def authorize_user(password: str, uid: str) -> bool:
I'll get on it

2021-07-29 14:41 UTC, AbooMinister25 commented on backend/src/database/crud/users.py
> +async def auth_token(token: str, uid: int) -> bool:
Alright

2021-07-29 15:07 UTC, Kronifer approved these changes
Looks good

2021-07-29 15:46 UTC, doublevcodes approved these changes
LGTM :shipit:

2021-07-29 15:46 UTC, merged