Added custom logger
cat-dev-group/catcord pull request #56
Opened 2021-07-05 20:44 UTC by Kronifer

We'll have fancy logs now

2021-07-05 21:05 UTC, AbooMinister25 requested changes
Alright, the general layout seems fine, but why is it a context manager? I don't really see a need for it to be one, most other logging libraries work fine without being a context manager. Its not really a *bad* design decision, but it may end up being unnecessarily verbose for general logging purposes.

2021-07-05 21:08 UTC, AbooMinister25 commented
Also, this isn't strictly required, but it might be nice to add a `success` and `debug` logging options.

2021-07-05 22:44 UTC, Kronifer commented
How do you mean

2021-07-19 07:00 UTC, doublevcodes commented on backend/core/logger.py
> +}
I am not sure ANSI escapes work on some Windows command prompts. Would it be better to import a formatting library

2021-07-19 07:00 UTC, doublevcodes commented on backend/core/logger.py
> +                )
There's probably a way of condensing this I just can't think of it

2021-07-28 15:50 UTC, dawnofmidnight commented
This is no longer needed as we're using [`loguru`](https://loguru.rtfd.io/).

2021-07-28 15:50 UTC, closed without merging