Added support for Tauri in the frontend.
cat-dev-group/catcord pull request #71
Opened 2021-07-17 23:31 UTC by AbooMinister25

Integrated Tauri with the frontend, React app can now be used on the desktop. We can edit the react app as normal as if nothing changed, just do `yarn tauri dev` to run it, it'll take some time to build for the first time, but after that it's pretty quick.

2021-07-18 14:52 UTC, Kronifer approved these changes
mmm, njes. looks hgood.

2021-07-19 15:46 UTC, dawnofmidnight requested changes
Seems pretty good, just this one thing.

2021-07-19 15:46 UTC, dawnofmidnight commented on frontend/package.json
> +    "tauri": "tauri",
This line is unnecessary.

2021-07-20 00:15 UTC, AbooMinister25 commented
> Seems pretty good, just this one thing.

Alright, I fixed the issue

2021-07-20 01:33 UTC, dawnofmidnight approved these changes

2021-07-20 01:33 UTC, merged